[versions]
activityCompose = "1.8.0"
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidLame = "1.0.0"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.3"
datastore = "1.1.7"
ffmpegKitFull = "6.1.4"
ffmpegKitMin = "4.5.1"
javaJwt = "4.5.0"
junit = "4.13.2"
kermit = "2.0.8"
kotlin = "2.2.21"
coilSvg = "3.3.0"
kotlinxSerializationJson = "1.9.0"
materialIconsExtended = "1.7.3"
media3Transformer = "1.8.0"
media3Common = "1.8.0"
navigationCompose = "2.9.1"
retrofit2KotlinxSerializationConverter = "1.0.0"
retrofit = "3.0.0"
converterGson = "3.0.0"
okhttp = "5.3.0"
gson = "2.13.2"
kotlinx-datetime = "0.7.1"
room = "2.8.3"
sqlite = "2.6.1"
ksp = "2.2.20-2.0.3"
media3CommonKtx = "1.8.0"
yandex-maps = "4.26.0-lite"
work-runtime-ktx = "2.10.0"
play-services-location = "21.3.0"
lifecycle-process = "2.8.4"

[libraries]
androidx-activity-compose-v180 = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Common" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3Transformer" }
ffmpeg-kit-full = { module = "com.mrljdx:ffmpeg-kit-full", version.ref = "ffmpegKitFull" }
ffmpeg-kit-min = { module = "com.arthenica:ffmpeg-kit-min", version.ref = "ffmpegKitMin" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilSvg" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilSvg" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
yandex-maps = { module = "com.yandex.android:maps.mobile", version.ref = "yandex-maps" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-process" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
